### ISSUE TITLE
Error in .Call2("cigar_qnarrow", cigar, width(threeranges$left), width(threeranges$right),  :    in 'cigar[256131]': CIGAR is empty after qnarrowing

### ISSUE THREAD

**Issue by U201412486** [jianhong/ribosomeProfilingQC#1]
Hi, 
   I run the code.
  ` cvgs.utr5.3 <- coverageDepth(RPFs = "test.bam", gtf = "annotation.gtf", region="utr5")`
   And it reported the error below.
   `Error in .Call2("cigar_qnarrow", cigar, width(threeranges$left), width(threeranges$right),  : 
  in 'cigar[256131]': CIGAR is empty after qnarrowing
`
  What happened?

**Comment by jianhong** [comment]
Thank you for trying ribosomeProfilingQC. This is because the reads length is too small. I will fix this bug soon.

**Comment by PFRoux** [comment]
Hi !

I am having the exact same issue.
Are you planning to fix it ? Is there another workaround ?

Thanks a lot.

Peu

**Comment by jianhong** [comment]
ou.jianhong@gmail.com

**Comment by jianhong** [comment]
Send already. Let me know if you did not receive it.

**Comment by PFRoux** [comment]
Thanks ! I got your email and sent to you a .bam file containing data generating the error.
Let me know if you did not receive it.

**Comment by jianhong** [comment]
It should be fixed. Let me know if there still have any issue.
