### ISSUE TITLE
 没有"RPFsCounts"这个函数

### ISSUE THREAD

**Issue by shwdmsh** [jianhong/ribosomeProfilingQC#2]
Hi,when I use these commands,some error info :
cnts <- countReads(RPFs, RNAs, gtf, level="tx")
Error in RPFsCounts(files = RPFs, txdb = txdb, level = level, bestpsite = bestpsite,  : 
  没有"RPFsCounts"这个函数

**Comment by jianhong** [comment]
Thank you for trying ribosomeProfilingQC.
May I know the R sessionInfo()? I think this is a issue in the installation.
