### ISSUE TITLE
readsDistribution plot information

### ISSUE THREAD

**Issue by tejas-j** [jianhong/ribosomeProfilingQC#4]
Using the readsDistribution, I can generate a plot. However, the percentage of OtherExon is very high compared to your example.
What exactly is OtherExon and how is it different from the CDS?

My sample is aligned to GRCh38 and I have used the GENCODE annotations gtf.

Thank you!

**Comment by jianhong** [comment]
please double check your gtf file by:

```{r}
  cdss <- cds(txdb)
  utr5 <- unlist(fiveUTRsByTranscript(txdb))
  utr3 <- unlist(threeUTRsByTranscript(txdb))
  exons <- exons(txdb)
  length(subsetByOverlaps(exons, cdss, invert=TRUE))
  length(subsetByOverlaps(exons, utr5, invert=TRUE))
  length(subsetByOverlaps(exons, utr3, invert=TRUE))
## check chrM
  length(pc.sub[seqnames(pc.sub)=='chrM'])
```

**Comment by tejas-j** [comment]
This is how it looks - 

```
> length(subsetByOverlaps(exons, cdss, invert=TRUE))
[1] 157442
> length(subsetByOverlaps(exons, utr5, invert=TRUE))
[1] 341413
> length(subsetByOverlaps(exons, utr3, invert=TRUE))
[1] 370205
> ## check chrM
> length(pc[seqnames(pc)=='chrM'])
[1] 80794
> length(exons)
[1] 432799
```

The GTF file that I used is here - 
https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_43/gencode.v43.basic.annotation.gtf.gz

Thank you

**Comment by jianhong** [comment]
Thank you for going deep. I will keep you posted once this is fixed.

**Comment by jianhong** [comment]
I add precedence parameter for the function. If no precedence specified, double count will be enabled. Let me know if you still have any questions.

**Comment by tejas-j** [comment]
Thank you very much @jianhong! It works as expected.
